# Generated by Django 3.2.22 on 2023-11-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
    ]
