# Generated by Django 3.2.22 on 2023-11-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cancelled',
        ),
    ]
